### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by mortoza** [tyl/field-binder#1]
Hi
I am trying to run the master detail view following the helper codes but getting an exceptions below:

```
Caused by: java.lang.NullPointerException
    at org.tylproject.vaadin.addon.fieldbinder.behavior.TableBehaviorFactory.forContainer(TableBehaviorFactory.java:53)
    at org.tylproject.vaadin.addon.datanav.BasicDataNavigation.withDefaultBehavior(BasicDataNavigation.java:325)
    at org.tylproject.vaadin.addon.fieldbinder.ListTable.buildDefaultEditorBar(ListTable.java:207)
    at org.tylproject.vaadin.addon.fieldbinder.ListTable.withDefaultEditorBar(ListTable.java:190)
    at com.inteacc.entity.PersonAddressView.initComponent(PersonAddressView.java:55)
    ... 70 more
```

line 55 contains the following codes;

``` java
                binder.buildListOf(TestOrderDetail.class, "addressList").withDefaultEditorBar()
        ).withFullWidth().withMargin(true);
```

The complete code of the view is as follows:

``` java
@CDIView("personaddressview")
public class PersonAddressView extends MVerticalLayout implements View {

    // CONTAINER
    // initialize an empty container
    final FilterableListContainer<Person2> container
            = new FilterableListContainer<Person2>(Person2.class);

    // FIELD BINDER 
    // initialize the FieldBinder for the given container
    final FieldBinder<Person2> binder = new FieldBinder<Person2>(Person2.class, container);
    VerticalLayout mainLayout;

    @PostConstruct
    public void initComponent() {

        // initialize the layout, building the fields at the same time
        mainLayout = new MVerticalLayout(
                // auto-generates a button bar with the appropriate behavior
                // for the underlying FilterableListContainer
                new ButtonBar(binder.getNavigation().withDefaultBehavior()),
                new MFormLayout(
                        // automatically generate a Field from the property type
                        binder.build("firstName"),
                        binder.build("lastName"),
                        binder.build("birthDate"),
                        binder.build("age"),
                        // optional: display the index of the currentItem in the container
                        new NavigationLabel(binder.getNavigation())
                ).withFullWidth().withMargin(true),
                // initialize the addressList field with a built-in button bar
                binder.buildListOf(TestOrderDetail.class, "addressList").withDefaultEditorBar()
        ).withFullWidth().withMargin(true);

        addComponent(mainLayout);

    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}

```

**Comment by evacchi** [comment]
Hi,

I think you are trying to use an outdated version of the FieldBinder Addon. Please update to **version 1.1**.

I can tell you are trying to use an outdated version of this addon because the method that causes the error (`TableBehaviorFactory.forContainer(TableBehaviorFactory.java:53)`) has changed signature (for one, it is now called `forContainerType()`).

Let me know if the issue still occurs on version 1.1 (it should not) and, if it doesn't, I will close this issue.

Thanks for supporting us with your bug report!

**Comment by mortoza** [comment]
Thanks. I tried to download version 1.1 but it seems only version 1.0 is available in Meven. I am using Netbeans and didn`t find a better way to install version 1.1 Any tips about version 1.1 to use in Netbeans?

**Comment by evacchi** [comment]
You might have to update Maven cache. Check whether you have the correct dependencies and repositories in your pom:

``` xml
<dependency>
   <groupId>org.tylproject.vaadin.addon.fieldbinder</groupId>
   <artifactId>field-binder</artifactId>
   <version>1.1</version>
</dependency>

<repository>
   <id>vaadin-addons</id>
   <url>http://maven.vaadin.com/vaadin-addons</url>
</repository>
```

**Comment by mortoza** [comment]
Yes I changed the version in Pom file to 1.1 version but download was not successful. I wonder if this version is there in Maven repository.

**Comment by evacchi** [comment]
I have just tried with a clean project and I had no problems. You might want to clean your `.m2` cache. Check whether you do have the `<repository>` section in your pom:

``` xml
<repository>
   <id>vaadin-addons</id>
   <url>http://maven.vaadin.com/vaadin-addons</url>
</repository>
```

**Comment by mortoza** [comment]
Hi
Thanks, I have cleaned the cache and now version 1.1 is downloaded and Now I can run the apps and the interface is showing up nicely. Looks great!

Now I need some help, how to save records in the database. I see two exceptions -
1) When the form is initiated, getting the following exception from enter method:

Info:   Returning view instance com.inteacc.entity.PersonAddressFieldBinderView@114555e6
Severe:   java.lang.UnsupportedOperationException: Not supported yet.
    at com.inteacc.entity.PersonAddressFieldBinderView.enter(PersonAddressFieldBinderView.java:74)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:577)

2) When I try to create a record, I get the following exceptions:
Severe:   com.vaadin.event.ListenerMethod$MethodException: Invocation of method itemCreate in org.tylproject.vaadin.addon.fieldbinder.behavior.ListContainerTableBehavior failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at org.tylproject.vaadin.addon.datanav.BasicDataNavigation.create(BasicDataNavigation.java:194)
    at org.tylproject.vaadin.addon.datanav.CrudButtonBar$1.buttonClick(CrudButtonBar.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

..........................
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 55 more
Caused by: java.lang.IllegalArgumentException: Error reading property 'total' nested exception - java.lang.NullPointerException
    at org.apache.commons.beanutils.WrapDynaBean.get(WrapDynaBean.java:138)
    at org.vaadin.viritin.ListContainer$DynaBeanItem$DynaProperty.getValue(ListContainer.java:358)
    at com.vaadin.ui.Table.formatPropertyValue(Table.java:4124)
    at com.vaadin.ui.Table.getPropertyValue(Table.java:4068)
    at com.vaadin.ui.Table.parseItemIdToCells(Table.java:2356)
    at com.vaadin.ui.Table.getVisibleCellsNoCache(Table.java:2195)
    at com.vaadin.ui.Table.refreshRenderedCells(Table.java:1717)

Another question, can I expect the data will be saved when I click Commit (after this issue is fixed)?
Note: I am using windows 7, vaadin 7.4 beta2, Java 8, Glassfish 4.1, netbeans 8

regards
Mortoza

**Comment by evacchi** [comment]
``` java
Info: Returning view instance com.inteacc.entity.PersonAddressFieldBinderView@114555e
Severe: java.lang.UnsupportedOperationException: Not supported yet.
at com.inteacc.entity.PersonAddressFieldBinderView.enter(PersonAddressFieldBinderView.java:74)
at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:577)
```

From what I can understand of this stacktrace, this does not look like something that depends on FieldBinder. 

``` java
Caused by: java.lang.IllegalArgumentException: Error reading property 'total' nested exception - java.lang.NullPointerException
at org.apache.commons.beanutils.WrapDynaBean.get(WrapDynaBean.java:138)
at org.vaadin.viritin.ListContainer$DynaBeanItem$DynaProperty.getValue(ListContainer.java:358)
```

Apparently the property "total" is not found in the JavaBean you are using? Are you initializing the Table widget correctly?

> Another question, can I expect the data will be saved when I click Commit (after this issue is fixed)?
> Note: I am using windows 7, vaadin 7.4 beta2, Java 8, Glassfish 4.1, netbeans 8

It depends on the backend you are using to perform the commit. The ListContainer is an in-memory container; it is used for detail-type forms, because the commit is actually performed by the button bar of the master view, _if_ the underlying container is supported. Otherwise you'll have to attach the `afterCommit` listener with `fieldBinder.getNavigation().addAfterCommitListener()` and write your custom logic.

**Comment by mortoza** [comment]
Hi Evacchi
Thanks for your reply and tips. I am glad that It works well, I can now save it to database. This is a very excellent add-on, you are awesome.

I am getting the following exception when running the apps, though it is working. Any further tips?

Severe:   java.lang.UnsupportedOperationException: Not supported yet.
    at com.inteacc.entity.PersonAddressFieldBinderView.enter(PersonAddressFieldBinderView.java:91)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:577)
    at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:526)
    at com.inteacc.util.ViewMenu.lambda$getButtonFor$d0c6f83b$1(ViewMenu.java:73)
    at com.inteacc.util.ViewMenu$$Lambda$5/872773535.buttonClick(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)

here is the complete code:

@CDIView("address2")
public class PersonAddressFieldBinderView extends MVerticalLayout implements View {

```
@Inject
Person2Facade facade;

Person2 person2;

FilterableListContainer<Person2> container;

FieldBinder<Person2> binder;
VerticalLayout mainLayout;

@PostConstruct
public void initComponent() {
    container = new FilterableListContainer<>(Person2.class);
    binder = new FieldBinder<>(Person2.class, container);            
    initFieldBinderListener();
    mainLayout = new MVerticalLayout(
            new ButtonBar(binder.getNavigation().withDefaultBehavior()),
            new MFormLayout(
                    binder.build("id"),
                    binder.build("firstName"),
                    binder.build("middleName"),
                    binder.build("lastName"),
                    binder.build("birthDate"),
                    binder.build("age"),
                    new NavigationLabel(binder.getNavigation())
            ).withFullWidth().withMargin(true),
            binder.buildListOf(Address2.class, "addressList").withDefaultEditorBar()
    ).withFullWidth().withMargin(true);

    addComponent(mainLayout);

}

@Override
public void enter(ViewChangeListener.ViewChangeEvent event) {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}
```

}

**Comment by evacchi** [comment]
well, your code does throw an exception.

``` java
@Override
public void enter(ViewChangeListener.ViewChangeEvent event) {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}
```

this is how Netbeans auto-generates methods, to remind you that you have not completed their implementation. You should probably get rid of it:

``` java
@Override
public void enter(ViewChangeListener.ViewChangeEvent event) {
}
```

**Comment by mortoza** [comment]
Excellent! Thank you so much for your help

Mortoza
