### ISSUE TITLE
Search Combobox-Value doesn't seem to Work with JPA

### ISSUE THREAD

**Issue by rbuchli** [tyl/field-binder#10]
Hi Evacchi
I'm trying to use default search  in my application. It works perfectly with text values, but fails with combobox-values. 
I have a table called tblgemeinde. There is another table called tblkanton. Each gemeinde (community) belongs to a kanton (Swiss expression for district).
The generated search window looks good, but if I search for a kanton (meaning I select a value from the generated combobox and press Apply) I get the following error. 
Is there anything I can do about it exept exclude the combobox from the search?
I'm using field-binder 1.3.

Thank you for having a look at it.
rbuchli

[EL Warning]: 2015-03-08 13:55:13.473--UnitOfWork(18137579)--Exception [EclipseLink-6078](Eclipse Persistence Services - 2.6.0.v20150210-f44015d): org.eclipse.persistence.exceptions.QueryException
Exception Description: The class of the argument for the object comparison is incorrect. 
Expression: [
Base ch.ludit.hangmuren.backend.data.Tblgemeinde] 
Mapping: [org.eclipse.persistence.mappings.ManyToOneMapping[tblkanton]] 
Argument: [AR]
Query: ReportQuery(referenceClass=Tblgemeinde )
Mär 08, 2015 1:55:23 PM com.vaadin.server.DefaultErrorHandler doDefault
SCHWERWIEGEND: 
com.vaadin.event.ListenerMethod$MethodException: Invocation of method windowClose in org.tylproject.vaadin.addon.fields.search.SearchWindow$4 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:977)
    at com.vaadin.ui.Window.fireClose(Window.java:417)
    at com.vaadin.ui.UI.removeWindow(UI.java:526)
    at com.vaadin.ui.Window.close(Window.java:244)
    at org.tylproject.vaadin.addon.fields.search.SearchWindow.apply(SearchWindow.java:159)
    at org.tylproject.vaadin.addon.fields.search.SearchWindow$1.buttonClick(SearchWindow.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:977)
    at com.vaadin.ui.Button.fireClick(Button.java:393)
    at com.vaadin.ui.Button$1.click(Button.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:291)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:184)
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method crudEnabled in org.tylproject.vaadin.addon.datanav.CrudButtonBar$6 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at org.tylproject.vaadin.addon.datanav.BasicDataNavigation.enableCrud(BasicDataNavigation.java:273)
    at org.tylproject.vaadin.addon.datanav.BasicDataNavigation.leaveClearToFind(BasicDataNavigation.java:344)
    at org.tylproject.vaadin.addon.datanav.BasicDataNavigation.find(BasicDataNavigation.java:311)
    at org.tylproject.vaadin.addon.fields.search.SearchWindow$4.windowClose(SearchWindow.java:118)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 53 more
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-6078](Eclipse Persistence Services - 2.6.0.v20150210-f44015d): org.eclipse.persistence.exceptions.QueryException
Exception Description: The class of the argument for the object comparison is incorrect. 
Expression: [
Base ch.ludit.hangmuren.backend.data.Tblgemeinde] 
Mapping: [org.eclipse.persistence.mappings.ManyToOneMapping[tblkanton]] 
Argument: [AR]
Query: ReportQuery(referenceClass=Tblgemeinde )
    at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:551)
    at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
    at com.vaadin.addon.jpacontainer.provider.LocalEntityProvider.doGetEntityCount(LocalEntityProvider.java:543)
    at com.vaadin.addon.jpacontainer.provider.CachingSupport$FilterCacheEntry.getEntityCount(CachingSupport.java:157)
    at com.vaadin.addon.jpacontainer.provider.CachingSupport.getEntityCount(CachingSupport.java:826)
    at com.vaadin.addon.jpacontainer.provider.CachingMutableLocalEntityProvider.getEntityCount(CachingMutableLocalEntityProvider.java:130)
    at com.vaadin.addon.jpacontainer.JPAContainer.size(JPAContainer.java:912)
    at org.tylproject.vaadin.addon.datanav.CrudButtonBar.updateButtonStatus(CrudButtonBar.java:156)
    at org.tylproject.vaadin.addon.datanav.CrudButtonBar$6.crudEnabled(CrudButtonBar.java:119)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 64 more
Caused by: Exception [EclipseLink-6078](Eclipse Persistence Services - 2.6.0.v20150210-f44015d): org.eclipse.persistence.exceptions.QueryException
Exception Description: The class of the argument for the object comparison is incorrect. 
Expression: [
Base ch.ludit.hangmuren.backend.data.Tblgemeinde] 
Mapping: [org.eclipse.persistence.mappings.ManyToOneMapping[tblkanton]] 
Argument: [AR]
Query: ReportQuery(referenceClass=Tblgemeinde )
    at org.eclipse.persistence.exceptions.QueryException.incorrectClassForObjectComparison(QueryException.java:601)
    at org.eclipse.persistence.mappings.OneToOneMapping.buildObjectJoinExpression(OneToOneMapping.java:298)
    at org.eclipse.persistence.internal.expressions.RelationExpression.normalize(RelationExpression.java:830)
    at org.eclipse.persistence.internal.expressions.SQLSelectStatement.normalize(SQLSelectStatement.java:1474)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.buildReportQuerySelectStatement(ExpressionQueryMechanism.java:642)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.buildReportQuerySelectStatement(ExpressionQueryMechanism.java:587)
    at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.prepareReportQuerySelectAllRows(ExpressionQueryMechanism.java:1696)
    at org.eclipse.persistence.queries.ReportQuery.prepareSelectAllRows(ReportQuery.java:1207)
    at org.eclipse.persistence.queries.ReadAllQuery.prepare(ReadAllQuery.java:798)
    at org.eclipse.persistence.queries.ReportQuery.prepare(ReportQuery.java:1075)
    at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:666)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.checkPrepare(ObjectLevelReadQuery.java:909)
    at org.eclipse.persistence.queries.DatabaseQuery.checkPrepare(DatabaseQuery.java:615)
    at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:872)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1132)
    at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:442)
    at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1220)
    at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
    at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
    at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
    at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:521)
    ... 77 more

**Comment by evacchi** [comment]
The search query is currently constructed by taking the `value` (as in `getValue()`) of the ComboBox of the Search field (called a "SearchComboBox"). Then it is given to the `DefaultFilterFactory`. The filter factory falls back to `Compare.Equal(boundPropertyId, value)` if the type of `value` is not recognized.

If I understand correctly, in your table "gemeinde" you want to be able to pick a "kanton" and perform a search by that "kanton". Therefore, the default behavior generates `Compare.Equal("kanton", <selected-kanton-id>)` --- I'm guessing here, but it seems consistent with the error you get. 

Now, I'm not really sure what EclipseLink expects here, but I suppose that comparing a value of type Kanton with its `id` is not correct.

**Comment by evacchi** [comment]
So, [here is (sort of) an answer](https://vaadin.com/forum#!/thread/4453022):

> Ir worked! I just use Filter filterAddress = new Compare.Equal("person.id", id));

Apparently, the filter is _really_ supposed to be `Compare.Equal("kanton.id", field.getValue())`. If you can get a reference to the `SearchPatternComboBox, you should be able to do the following:

``` java
SearchPatternComboBox f = ...;
f.setFilterFactory(new DefaultFilterFactory() {
  @Override
  public Container.Filter createFilter(Class<?> targetType, Object targetPropertyId, Object pattern) {
     if (targetPropertyId.equals("kanton") && pattern != null) {
       return new Compare.Equal("kanton.id", pattern); 
     }
     else return super.createFilter(targetType, targetPropertyId, pattern);
  }
});
```

I'm not sure how to fix it in core FieldBinder, I'll have to think about it. Search was the only part that was not special-cased for Container types, I wish I could keep it like that (sigh!)

**Comment by evacchi** [comment]
Another workaround you may try is to bind the Form to the "kanton.id" propertyId at construction time, then specify that you want a ComboBox, with

``` java
  ComboBox kantonId = binder.build("kanton.id", ComboBox.class);
```

then, specify that the source of those ids will be the "kanton" table using manual ComboBox configuration

``` java
  kantonId.setItemDataSource(JPAContainer.makeContainer(...));
```

**Comment by evacchi** [comment]
BTW, I tried to reproduce your problem and I can't. ComboBoxes should show only if the property type is an enum. Is this the case for `kanton` ?

**Comment by rbuchli** [comment]
Hi
No, it isn't, it is a String. Here are the two table definitions (see below).
For your information: I tried your proposal to use the field kanton (example: "AG", "ZH").
This fails with a not existing field exception.
I have to use:

``` java
    // Create a container for kanton
    JPAContainer<Tblkanton> kantonecontainer;
    kantonecontainer = JPAContainerFactory.makeBatchable(Tblkanton.class,
        ProjectConstants.PERSISTENCE_UNIT_NAME);

    tblkanton = binder.build("Kanton", "tblkanton", ComboBox.class);
    tblkanton.setContainerDataSource(kantonecontainer);
    tblkanton.setInputPrompt("Bitte Kanton wählen");
```

Which means, I create a combobox using the table field for tblkanton on the edit tblgemeinde.
And with this I get my exception.
I'm now trying to use your proposal with SearchPatternComboBox.
I was using

``` java
    SearchWindowFindListeners findListeners = new SearchWindowFindListeners(binder);
    Behavior listeners = new BehaviorFacade(
        new FieldBinders.CurrentItemChangeListener<Tblgemeinde>(binder),
        new JPAContainerCrud<Tblgemeinde>(binder), findListeners);
```

to create the search part. But probably I can't use the default way here.

But anyway, here are the table definitions (generated with JPA-Tools):

## tblgemeinde

``` java
package ch.ludit.project.backend.data;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * The persistent class for the tblgemeinde database table.
 */
@Entity
@Table(name="tblgemeinde")
@NamedQuery(name="Tblgemeinde.findAll", query="SELECT t FROM Tblgemeinde t")
public class Tblgemeinde extends ProjectModel {
    private static final long serialVersionUID = 1L;
    @Id
    @Column(unique=true, nullable=false, length=40)
    private String gemeinde;
    //bi-directional many-to-one association to Tblkanton
    @ManyToOne
    @JoinColumn(name="kanton", nullable=false)
    private Tblkanton tblkanton;
    //bi-directional many-to-one association to Tblkoord
    @OneToMany(mappedBy="tblgemeinde")
    private List<Tblkoord> tblkoordinaten;
    //bi-directional many-to-one association to Tbllokalname
    @OneToMany(mappedBy="tblgemeinde")
    private List<Tbllokalname> tbllokalnamen;
    public Tblgemeinde() {
    }
    public String getGemeinde() {
        return this.gemeinde;
    }
    public void setGemeinde(String gemeinde) {
        this.gemeinde = gemeinde;
    }
    public Tblkanton getTblkanton() {
        return this.tblkanton;
    }
    public void setTblkanton(Tblkanton tblkanton) {
        this.tblkanton = tblkanton;
    }
    public List<Tblkoord> getTblkoordinaten() {
        return this.tblkoordinaten;
    }
    public void setTblkoordinaten(List<Tblkoord> tblkoordinaten) {
        this.tblkoordinaten = tblkoordinaten;
    }
    public Tblkoord addTblkoordinaten(Tblkoord tblkoordinaten) {
        getTblkoordinaten().add(tblkoordinaten);
        tblkoordinaten.setTblgemeinde(this);
        return tblkoordinaten;
    }
    public Tblkoord removeTblkoordinaten(Tblkoord tblkoordinaten) {
        getTblkoordinaten().remove(tblkoordinaten);
        tblkoordinaten.setTblgemeinde(null);
        return tblkoordinaten;
    }
    public List<Tbllokalname> getTbllokalnamen() {
        return this.tbllokalnamen;
    }
    public void setTbllokalnamen(List<Tbllokalname> tbllokalnamen) {
        this.tbllokalnamen = tbllokalnamen;
    }
    public Tbllokalname addTbllokalnamen(Tbllokalname tbllokalnamen) {
        getTbllokalnamen().add(tbllokalnamen);
        tbllokalnamen.setTblgemeinde(this);
        return tbllokalnamen;
    }
    public Tbllokalname removeTbllokalnamen(Tbllokalname tbllokalnamen) {
        getTbllokalnamen().remove(tbllokalnamen);
        tbllokalnamen.setTblgemeinde(null);
        return tbllokalnamen;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Tblgemeinde [gemeinde=");
        builder.append(gemeinde);
        builder.append(", tblkanton=");
        builder.append(tblkanton);
        builder.append("]");
        return builder.toString();
    }
    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((gemeinde == null) ? 0 : gemeinde.hashCode());
        return result;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Tblgemeinde other = (Tblgemeinde) obj;
        if (gemeinde == null) {
            if (other.gemeinde != null) {
                return false;
            }
        } else if (!gemeinde.equals(other.gemeinde)) {
            return false;
        }
        return true;
    }
}
```

## tblkanton

``` java
package ch.ludit.project.backend.data;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * The persistent class for the tblkanton database table.
 */
@Entity
@Table(name="tblkanton")
@NamedQuery(name="Tblkanton.findAll", query="SELECT t FROM Tblkanton t")
public class Tblkanton extends ProjectModel {
    private static final long serialVersionUID = 1L;
    @Id
    @Column(unique=true, nullable=false, length=2)
    private String kanton;
    @Column(nullable=false, length=40)
    private String bezeichnung;
    //bi-directional many-to-one association to Tblgemeinde
    @OneToMany(mappedBy="tblkanton")
    private List<Tblgemeinde> tblgemeinden;
    //bi-directional many-to-one association to Tblland
    @ManyToOne
    @JoinColumn(name="land", nullable=false)
    private Tblland tblland;
    public Tblkanton() {
    }
    public String getKanton() {
        return this.kanton;
    }
    public void setKanton(String kanton) {
        this.kanton = kanton;
    }
    public String getBezeichnung() {
        return this.bezeichnung;
    }
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }
    public List<Tblgemeinde> getTblgemeinden() {
        return this.tblgemeinden;
    }
    public void setTblgemeinden(List<Tblgemeinde> tblgemeinden) {
        this.tblgemeinden = tblgemeinden;
    }
    public Tblgemeinde addTblgemeinden(Tblgemeinde tblgemeinden) {
        getTblgemeinden().add(tblgemeinden);
        tblgemeinden.setTblkanton(this);
        return tblgemeinden;
    }
    public Tblgemeinde removeTblgemeinden(Tblgemeinde tblgemeinden) {
        getTblgemeinden().remove(tblgemeinden);
        tblgemeinden.setTblkanton(null);
        return tblgemeinden;
    }
    public Tblland getTblland() {
        return this.tblland;
    }
    public void setTblland(Tblland tblland) {
        this.tblland = tblland;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Tblkanton [kanton=");
        builder.append(kanton);
        builder.append("]");
        return builder.toString();
    }
    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((kanton == null) ? 0 : kanton.hashCode());
        return result;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Tblkanton other = (Tblkanton) obj;
        if (kanton == null) {
            if (other.kanton != null) {
                return false;
            }
        } else if (!kanton.equals(other.kanton)) {
            return false;
        }
        return true;
    }
}
```

**Comment by rbuchli** [comment]
To be more precise. What I said before is partially wrong.
1. Your solution with 

``` Java
tblkanton = binder.build("Kanton", "tblkanton.kanton", ComboBox.class);
```

partially works (I had a typo before, that's why I got an exception). 
If I use this, the search really works. But then the commit of a changed kanton fails, because the update does not now where to put the new kanton. So I still have to use "tblkanton" in the original form.
2. You were right, I don't see a combobox in the search form anymore. I don't know, where this has come from. 
This means: I'm still trying to find a reference to the search field, but not combobox but textfield.

**Comment by evacchi** [comment]
> If I use this, the search really works. But then the commit of a changed kanton fails, because the update does not now where to put the new kanton. So I still have to use "tblkanton" in the original form.

as a workaround, you can hook the valueChange event and set the `tblkanton` for the currently selected `tblktanton.kanton` in the currently selected item of the `tblgemeinde`

> This means: I'm still trying to find a reference to the search field, but not combobox but textfield.

you should be able to do this:

``` java
    SearchForm searchForm = new SearchForm(fieldBinder);
    SearchWindowFindListeners findListeners = new SearchWindowFindListeners(searchForm);
    ...
    SearchFieldManager sfm = searchForm.getSearchFieldManager();
    SearchPatternField<?,?> sptf = sfm.getSearchPatternField("tblkanton.kanton"); // you can cast it to SearchPatternTextField, but it is not needed
    sptf.setFilterFactory( /* ... code here ... */);
```

**Comment by rbuchli** [comment]
**Great!** Now it works.
Thank you very much for your support. This helped a lot.

Just if anyone is following:
As proposed I used this code:

``` Java
SearchForm searchForm = new SearchForm(binder);
SearchWindow searchWindow = new SearchWindow(searchForm);
SearchWindowFindListeners findListeners = new SearchWindowFindListeners(searchWindow);

SearchFieldManager sfm = searchForm.getSearchFieldManager();
Map<Object, SearchPatternField<?,?>> map = sfm.getPropertyIdToSearchPatternField();
SearchPatternField sptf = map.get("tblkanton");

sptf.setFilterFactory(new FilterFactory() {
    @Override
    public Filter createFilter(Class<?> targetType, Object targetPropertyId,
            Object pattern) {
        /*
         * use standard filter but with kanton id, not tblkanton
         */
        SimpleStringFilter filter = new SimpleStringFilter("tblkanton.kanton", (String) pattern, 
                      true, false);
        return filter;
    }
});

Behavior listeners = new BehaviorFacade(
    new FieldBinders.CurrentItemChangeListener<Tblgemeinde>(binder),
    new JPAContainerCrud<Tblgemeinde>(binder), findListeners);

ButtonBar bar = new ButtonBar(binder.getNavigation().withBehavior(listeners));
```
